version: '3.8'

services:
  mario-gan:
    container_name: mario-gan
    image: us-docker.pkg.dev/colab-images/public/runtime
    command: >
      jupyter-lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''
    tty: true
    privileged: true
    network_mode: "host"
    runtime: nvidia
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - ./:/mario-gan
    working_dir: /mario-gan
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.docker.xauth
